admin_page_limit: '10'
admin_date_format: 'd F, Y'
admin_date_time_format: 'd F, Y H:i A'
main_logo: theme_images/1753953806_688b360e75893.svg
main_favicon: theme_images/1753953819_688b361bc5798.ico
industry: ecommerce
